name: successhunter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.6.2+1
  google_sign_in: ^3.2.4
  flutter_facebook_login: ^1.1.1
  font_awesome_flutter: ^8.0.1
  flutter_circular_chart: ^0.1.0
  percent_indicator: ^1.0.9
  intl: ^0.15.7
  card_settings: ^1.2.2
  cloud_firestore: ^0.8.2+3
  flutter_slidable: ^0.4.9
  json_annotation: ^2.0.0
  share: ^0.5.3
  firebase_messaging: ^2.0.3
  flutter_calendar_carousel: ^1.1.10
  tinycolor: ^1.0.2
  flutter_charts: ^0.1.10
  charts_flutter: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.1
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  assets:
        # background for header
        - assets/img/book.png
        - assets/img/calendar.png
        - assets/img/multitarget.png
        - assets/img/person.png
        - assets/img/statistics.png
        - assets/img/target.png
        # avatar
        - assets/avatar/boss.png
        - assets/avatar/kid.png
        - assets/avatar/new_officer.png
        - assets/avatar/old_officer.png
        - assets/avatar/student.png
        - assets/avatar/teenager.png
        # badge
        - assets/badge/coop_1.png
        - assets/badge/coop_5.png
        - assets/badge/coop_10.png
        - assets/badge/coop_50.png
        - assets/badge/coop_100.png
        - assets/badge/goal_1.png
        - assets/badge/goal_5.png
        - assets/badge/goal_10.png
        - assets/badge/goal_50.png
        - assets/badge/goal_100.png
        - assets/badge/habit_1.png
        - assets/badge/habit_5.png
        - assets/badge/habit_10.png
        - assets/badge/habit_50.png
        - assets/badge/habit_100.png
        - assets/badge/streak_5.png
        - assets/badge/streak_10.png
        - assets/badge/streak_50.png
        - assets/badge/streak_100.png
        - assets/badge/level_1.png
        - assets/badge/level_10.png
        - assets/badge/level_20.png
        - assets/badge/level_30.png
        - assets/badge/level_40.png
        - assets/badge/level_50.png
        # flare animation
        - assets/flare/loading.flr

  fonts:
      - family: RobotoBold
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Bold.ttf

      - family: RobotoMedium
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Medium.ttf

      - family: RobotoRegular
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Regular.ttf