const Map<String, String> badgeNames = {
  'coop_1.png': 'You have finished a co-op goal.',
  'coop_5.png': 'You have finished 5 co-op goals.',
  'coop_10.png': 'You have finished 10 co-op goals.',
  'coop_50.png': 'You have finished 50 co-op goals.',
  'coop_100.png': 'You have finished 100 co-op goals.',
  'goal_1.png': 'You have finished a goal.',
  'goal_5.png': 'You have finished 5 goals.',
  'goal_10.png': 'You have finished 10 goals.',
  'goal_50.png': 'You have finished 50 goals.',
  'goal_100.png': 'You have finished 100 goals.',
  'habit_1.png': 'You have finished a habit task.',
  'habit_5.png': 'You have finished 5 habit tasks.',
  'habit_10.png': 'You have finished 10 habit tasks.',
  'habit_50.png': 'You have finished 50 habit tasks.',
  'habit_100.png': 'You have finished 100 habit tasks.',
  'streak_5.png': 'You have completed a 5-time streak.',
  'streak_10.png': 'You have completed a 10-time streak.',
  'streak_50.png': 'You have completed a 50-time streak.',
  'streak_100.png': 'You have completed a 100-time streak.',
  'level_1.png': 'You have leveled up',
  'level_10.png': 'You have reached level 10.',
  'level_20.png': 'You have reached level 20.',
  'level_30.png': 'You have reached level 30.',
  'level_40.png': 'You have reached level 40.',
  'level_50.png': 'You have reached level 50.',
};
